server:
  port: 8761

spring:
  application:
    name: eureka
  profiles: 
    active: server
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
